//go:build (windows && gui && tk) || (linux && gui)

package main

// Tk UI backend (Windows / Linux), providing the same startLogging / runUI as the
// Win32 gui.go / win32.go; build tags pick one:
//
//	Windows: compiled only with explicit -tags gui,tk (default stays Win32, pure SDK)
//	Linux:   compiled with -tags gui (no Win32 on Linux)
//
// Uses modernc.org/tk9.0 (pure-Go port of Tk 9.0, no CGO, no bundled DLL):
//   - Complex static layout (top bar / tabs / text + scrollbars) is still built by a Tcl
//     script via eval.Eval — proven under Tk 8.6, and the commands are fully Tk 9.0
//     compatible.
//   - Callback-needing parts (button clicks, window close, periodic refresh) use the
//     tk9.0 native API: Command(func()) for buttons, self-rescheduling
//     TclAfter(ms, func()) for refresh, WmProtocol(func()) for close. That drops CGO and
//     avoids registering custom Tcl commands.
//
// Threading: tk9.0 must be called from the goroutine that initialized it (it locks the OS
// thread internally). Every eval / TclAfter / WmProtocol / Command callback runs on the Tk
// event-loop thread, so calling Tk from the refresh is safe; the HTTP server runs on another
// goroutine and never touches Tk. Window close goes through the WmProtocol callback, which
// os.Exit()s the whole process (the monitoring backend goes with it).

import (
	_ "embed"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	. "modernc.org/tk9.0"
	. "modernc.org/tk9.0/extensions/eval"
)

// App icons (same source as the Win32 build, both generated by tools/make_icon.py).
//
// Tk's wm iconphoto only accepts image formats; PNG is natively supported by Tk 9.0, so we
// embed PNGs rather than src/icon/app.ico. Three sizes because Windows picks one per
// context: with only 256 the 16px title-bar icon would be scaled down and look blurry.
// The three together are ~14KB, acceptable.
//
//go:embed icon/icon256.png
var tkIcon256 []byte

//go:embed icon/icon48.png
var tkIcon48 []byte

//go:embed icon/icon16.png
var tkIcon16 []byte

// tkEval runs a Tcl script; on non-TCL_OK it logs the error without panicking
// (the UI keeps running).
func tkEval(script string) error {
	if _, err := Eval(script); err != nil {
		log.Println(T("log.tk_tcl_error", err, script))
		return err
	}
	return nil
}

// tkSetVar puts a string into a Tcl global so scripts can reference it as $var: any
// content (braces, newlines, backslashes) reaches Tk safely with no escaping. Evalv
// performs no Tcl substitution, so the value is written as a literal and its special
// characters are never parsed by Tcl.
func tkSetVar(name, val string) {
	if _, err := Evalv("set", name, val); err != nil {
		log.Println(T("log.tk_set_var", name, err))
	}
}

// tkSetText writes text into a text widget: unlock → clear → insert → lock read-only.
// The widget stays -state disabled otherwise: view/scroll/select only, no editing.
func tkSetText(path, content string) {
	tkSetVar("::tkbuf", content)
	script := fmt.Sprintf(
		"%s configure -state normal; %s delete 1.0 end; %s insert end $::tkbuf; %s configure -state disabled",
		path, path, path, path)
	if err := tkEval(script); err != nil {
		log.Println(T("log.tk_update", path, err))
	}
}

// tkSetLabel writes text into a label (via -text, not the text widget's insert/delete).
func tkSetLabel(path, content string) {
	tkSetVar("::tkbuf", content)
	if err := tkEval(fmt.Sprintf("%s configure -text $::tkbuf", path)); err != nil {
		log.Println(T("log.tk_update", path, err))
	}
}

// buildUIScript returns the Tcl script that creates the whole widget tree (purely
// static, no user data). The main window uses grid, more predictable than pack, and the
// tabs use it too so the notebook really fills the remaining space instead of collapsing
// to transparent/blank. The bottom button row and the window-close protocol are handled
// by the native API (see runTk), hence no .btns or wm protocol here.
func buildUIScript() string {
	var b strings.Builder
	// Font convention: always use bare named fonts (TkDefaultFont / TkTextFont /
	// TkFixedFont / TitleFont) and set the size via font configure. ⚠️ Never write a
	// "name space size" spec like "TkTextFont 10" — Tk9 treats TkTextFont as a family name,
	// fails to match it, and silently falls back to a default serif (measured:
	// font actual {TkTextFont 10} -family → the CJK default), which disagrees with tabs
	// and other widgets that use bare named fonts.
	b.WriteString(`catch {font configure TkDefaultFont -size 11}
catch {font configure TkTextFont -size 10}
catch {font configure TkFixedFont -size 10}
catch {font create TitleFont -family [font actual TkDefaultFont -family] -size 16}
catch {font create TkSmallFont -family [font actual TkDefaultFont -family] -size 9}
wm title . "` + appTitle() + `"
wm geometry . 1240x860
wm minsize . 860 560
ttk::style configure TLabel -font TkDefaultFont
ttk::style configure TButton -font TkDefaultFont
# Two state-line colors: ttk widgets reject configure -foreground, so use the style system
ttk::style configure StateNormal.TLabel -font TkTextFont -foreground #000000
ttk::style configure StateError.TLabel  -font TkTextFont -foreground #cc0000

# Top bar
ttk::frame .top
grid .top -row 0 -column 0 -sticky ew -padx 8 -pady 6
ttk::label .top.title -text "` + appTitle() + `" -font TitleFont
ttk::label .top.upd -text "` + T("status.updated_dash") + `"
grid .top.title -row 0 -column 0 -sticky w
grid .top.upd -row 0 -column 1 -sticky w -padx 12
grid columnconfigure .top 1 -weight 1

# Notebook widget
ttk::notebook .nb
grid .nb -row 1 -column 0 -sticky nsew -padx 8 -pady 6
grid rowconfigure . 1 -weight 1
grid columnconfigure . 0 -weight 1

# ---- Run-status page ----
ttk::frame .nb.s
.nb add .nb.s -text "` + T("tab.status") + `"
ttk::label .nb.s.info -text "" -justify left -anchor nw -wraplength 1180 -font TkTextFont
ttk::label .nb.s.state -text "` + T("app.init") + `" -style StateNormal.TLabel
text .nb.s.log -width 110 -height 12 -wrap word -font TkTextFont -state disabled -yscrollcommand {.nb.s.sby set}
ttk::scrollbar .nb.s.sby -orient vertical -command {.nb.s.log yview}
grid .nb.s.info -row 0 -column 0 -columnspan 2 -sticky new -padx 6 -pady 2
grid .nb.s.state -row 1 -column 0 -columnspan 2 -sticky ew -padx 6 -pady 2
grid .nb.s.log -row 2 -column 0 -sticky nsew -padx 6 -pady 2
grid .nb.s.sby -row 2 -column 1 -sticky ns -padx 0 -pady 2
grid rowconfigure .nb.s 2 -weight 1
grid columnconfigure .nb.s 0 -weight 1

# ---- Data-panel page ----
ttk::frame .nb.d
.nb add .nb.d -text "` + T("tab.data") + `"
.nb select .nb.d
`)
	for _, sec := range []struct {
		caption string
		base    string
		font    string
	}{
		{T("tab.summary"), "stat", "TkTextFont"},
		{T("tab.ship"), "ship", "TkTextFont"},
		{T("tab.bounty"), "bounty", "TkFixedFont"},
		{T("tab.events"), "msg", "TkTextFont"},
	} {
		f := ".nb.d.f_" + sec.base
		t := ".nb.d." + sec.base
		width, height := 55, 7
		if sec.base == "stat" || sec.base == "ship" {
			width, height = 52, 6
		}
		fmt.Fprintf(&b, `ttk::labelframe %s -text "%s"
text %s -width %d -height %d -wrap word -font "%s" -state disabled -yscrollcommand {%s.sby set}
ttk::scrollbar %s.sby -orient vertical -command {%s yview}
pack %s.sby -in %s -side right -fill y
pack %s -in %s -side left -fill both -expand 1 -padx 2 -pady 1
`, f, sec.caption, t, width, height, sec.font, f, f, t, f, f, t, f)
	}
	b.WriteString(`grid .nb.d.f_stat -row 0 -column 0 -sticky nsew -padx 6 -pady 2
grid .nb.d.f_ship -row 0 -column 1 -sticky nsew -padx 6 -pady 2
grid .nb.d.f_bounty -row 1 -column 0 -sticky nsew -padx 6 -pady 2
grid .nb.d.f_msg -row 1 -column 1 -sticky nsew -padx 6 -pady 2
grid rowconfigure .nb.d 0 -weight 0
grid rowconfigure .nb.d 1 -weight 1
grid columnconfigure .nb.d 0 -weight 1
grid columnconfigure .nb.d 1 -weight 1

# ---- Kill-trend page: the same chart the web panel draws ----
# A plain canvas, everything inside it is drawn by Go each refresh (tkDrawTrend).
# highlightthickness 0 removes the focus ring Tk draws around the widget by default,
# and the background is taken from the theme so it matches every other page.
ttk::frame .nb.t
.nb add .nb.t -text "` + T("panel.trend_title") + `"
canvas .nb.t.c -highlightthickness 0 -background [ttk::style lookup TFrame -background]
grid .nb.t.c -row 0 -column 0 -sticky nsew -padx 6 -pady 2
grid rowconfigure .nb.t 0 -weight 1
grid columnconfigure .nb.t 0 -weight 1

# ---- Bottom status bar (HTTP state / panel address / kills / kills (1h) / mission progress / bounty), same content as Win32 ----
# Placed below the button row: buttons are the window's actions, the status bar is the window's state.
# Cells change at runtime (kills, mission progress and bounty keep counting), so the Go side
# refills them every refresh tick (tkStatusBar).
ttk::separator .sbline -orient horizontal
grid .sbline -row 3 -column 0 -sticky ew -pady 0
ttk::frame .sb
grid .sb -row 4 -column 0 -sticky ew -padx 8 -pady 3
foreach p {p0 p1 p2 p3 p4 p5} {
	ttk::label .sb.$p -text "" -anchor w -font TkTextFont
}
# The panel address is a link: blue plus underline. ttk ignores -foreground, so the colour goes
# through a style; the underline needs a font of its own, derived from TkTextFont via
# [font actual] so it inherits the theme's family and size instead of naming a font (a bare
# "TkTextFont 10" string is read as a family name and silently falls back to SimSun).
font create SbLinkFont -family [font actual TkTextFont -family] -size [font actual TkTextFont -size] -underline 1
ttk::style configure Link.TLabel -foreground #005AC0
.sb.p1 configure -font SbLinkFont -style Link.TLabel
grid .sb.p0 -row 0 -column 0 -sticky ew -padx 6
grid .sb.p1 -row 0 -column 1 -sticky w -padx 6
grid .sb.p2 -row 0 -column 2 -sticky w -padx 6
grid .sb.p3 -row 0 -column 3 -sticky w -padx 6
grid .sb.p4 -row 0 -column 4 -sticky w -padx 6
grid .sb.p5 -row 0 -column 5 -sticky w -padx 6
# Bounty (p5) fills the right edge, matching the Win32 status bar's last segment (-1); the
# other cells keep their natural width and pack left, so the address (p1) sits right after the
# state label and is a stable, clickable target.
grid columnconfigure .sb 5 -weight 1
`)
	return b.String()
}

// tkStatLast caches what the bottom status bar currently shows so the per-tick refresh only
// talks to Tcl about cells that actually changed (kills / mission progress / bounty tick over slowly).
var tkStatLast [6]string

// tkStatusBar fills the bottom status bar: HTTP state / panel address / total kills / mission
// progress / total bounty. Content comes from the same shared source as the Win32 build (statusBarParts).
func tkStatusBar(st AppStatus) {
	for i, txt := range statusBarParts(st) {
		if tkStatLast[i] == txt {
			continue
		}
		tkStatLast[i] = txt
		tkSetLabel(fmt.Sprintf(".sb.p%d", i), txt)
	}
}

// tkRefresh runs on the Tk event-loop thread (self-rescheduled every 500ms via
// TclAfter): grab a fresh snapshot and refresh every widget. The next tick is always
// scheduled, so the UI keeps refreshing even if this one errored.
func tkRefresh() {
	defer func() {
		// Self-reschedule each tick; TclAfter queues the Go callback onto the Tk thread,
		// so this is thread-safe.
		TclAfter(500*time.Millisecond, tkRefresh)
	}()

	st := snapshotStatus()

	// Bottom status bar (panel state / total kills / total bounty)
	tkStatusBar(st)

	// Top "updated at"
	tkSetVar("::tkbuf", T("status.updated", st.UpdatedAt))
	tkEval(".top.upd configure -text $::tkbuf")

	// Status line (red on error) — ttk widgets don't support configure -fg/-foreground,
	// so the color must change by switching style (buildUIScript defines the
	// StateNormal / StateError styles).
	state, red := stateText(st)
	style := "StateNormal.TLabel"
	if red {
		style = "StateError.TLabel"
	}
	tkSetVar("::tkbuf", state)
	tkEval(fmt.Sprintf(".nb.s.state configure -text $::tkbuf -style %s", style))

	// Running status tab: summary + recent log
	tkSetLabel(".nb.s.info", buildSummary(st))
	tkSetText(".nb.s.log", strings.Join(recentLogLines(400), "\n"))

	// Data panel tab
	tkSetText(".nb.d.stat", buildSummary(st))
	tkSetText(".nb.d.ship", buildShip(st))

	var bb strings.Builder
	for i := len(st.BountyRecords) - 1; i >= 0; i-- {
		r := st.BountyRecords[i]
		ship := r.ShipType
		if ship == "" {
			if r.IsMission {
				ship = T("bounty.mission")
			} else {
				ship = T("bounty.unknown_ship")
			}
		}
		fmt.Fprintf(&bb, "%s  %13s  %s\n", r.TimeLocal, commas(r.Credits)+" Cr", ship)
	}
	tkSetText(".nb.d.bounty", bb.String())

	var mb strings.Builder
	for i := len(st.MessageLines) - 1; i >= 0; i-- {
		mb.WriteString(st.MessageLines[i] + "\n")
	}
	tkSetText(".nb.d.msg", mb.String())

	tkDrawTrend(st)
}

// tkTrendCanvas is the chart's canvas, created by buildUIScript.
const tkTrendCanvas = ".nb.t.c"

// tkTrendState remembers the last frame drawn, so the chart is only rebuilt when
// something actually changed: new data, or a resized window (the canvas has no
// fixed size, it follows the notebook, and a resize changes the whole layout).
var tkTrendState struct {
	sig   trendKey
	w, h  int
	hover int  // bucket under the cursor, -1 for none
	stale bool // a hover change forces the next draw through the signature check
	drawn bool
}

// tkDrawTrend draws the trend chart as canvas items. It is the Tk twin of the
// Win32 build's drawTrend and shares its geometry — see trendchart.go.
//
// Every string travels through a Tcl variable and the script only dereferences
// it. Inlining text into the script would let a translation containing "$" or
// "[" be interpreted as code, and language files are user-editable.
func tkDrawTrend(st AppStatus) {
	w, h := tkWidgetSize(tkTrendCanvas)
	if w < 2 || h < 2 {
		return // not mapped yet; the next tick will see it
	}
	sig := trendSignature(st)
	if tkTrendState.drawn && !tkTrendState.stale &&
		sig == tkTrendState.sig && w == tkTrendState.w && h == tkTrendState.h {
		return
	}
	tkTrendState.sig, tkTrendState.w, tkTrendState.h = sig, w, h
	tkTrendState.drawn, tkTrendState.stale = true, false

	c := buildTrendChart(st.KillTrend, st.TrendWindowText, int32(w), int32(h))

	var (
		b strings.Builder
		n int
	)
	// ref writes text into a fresh global and returns how to dereference it
	ref := func(s string) string {
		name := fmt.Sprintf("::tv%d", n)
		n++
		tkSetVar(name, s)
		return "$" + name
	}

	// Colours are asked of the theme where possible: hardcoded ones would be
	// invisible or garish under a dark theme. The curves keep the hues the web
	// panel uses, darkened for a light face (same as the Win32 build).
	b.WriteString("set ::tkfg [ttk::style lookup TLabel -foreground]\n")
	if c.Empty {
		fmt.Fprintf(&b, "%s delete all\n", tkTrendCanvas)
		fmt.Fprintf(&b, "%s create text %d %d -text %s -anchor center -justify center -fill $::tkfg\n",
			tkTrendCanvas, w/2, h/2, ref(c.Note))
		tkEval(b.String())
		return
	}

	b.WriteString(fmt.Sprintf("%s delete all\n", tkTrendCanvas))

	// Grid rows and their tick numbers; the numbers sit beside the right-hand column
	for _, tk := range c.Ticks {
		fmt.Fprintf(&b, "%s create line 0 %d %d %d -fill %s -width 1\n",
			tkTrendCanvas, tk.Y, c.AxisX, tk.Y, tkColorGrid)
		fmt.Fprintf(&b, "%s create text %d %d -text %s -anchor w -fill $::tkfg -font TkSmallFont\n",
			tkTrendCanvas, c.AxisX+6, tk.Y, ref(tk.Text))
	}
	// Unit for those bare numbers
	fmt.Fprintf(&b, "%s create text %d %d -text %s -anchor sw -fill $::tkfg -font TkSmallFont\n",
		tkTrendCanvas, c.AxisX+6, 14, ref(c.Unit))

	// Clock times, hanging from the bottom axis
	for _, lb := range c.Labels {
		fmt.Fprintf(&b, "%s create text %d %d -text %s -anchor n -fill $::tkfg -font TkSmallFont\n",
			tkTrendCanvas, lb.X, lb.Y, ref(lb.Text))
	}

	// Legend: a swatch per curve, each label followed by the next swatch. Widths
	// are measured because the labels are translated - a fixed pitch would
	// overlap in any language longer than the one it was tuned for.
	lx, ly := 8, 4
	for _, it := range []struct{ color, text string }{
		{tkColorRate, c.LegendRate}, {tkColorHour, c.LegendHour},
	} {
		fmt.Fprintf(&b, "%s create rectangle %d %d %d %d -fill %s -outline %s\n",
			tkTrendCanvas, lx, ly+3, lx+11, ly+14, it.color, it.color)
		name := ref(it.text)
		fmt.Fprintf(&b, "%s create text %d %d -text %s -anchor nw -fill $::tkfg -font TkSmallFont\n",
			tkTrendCanvas, lx+16, ly, name)
		lx += 16 + tkFontWidth("TkSmallFont", name) + 18
	}
	// The covered span follows the legend on the same row (as in the web panel),
	// rather than being right-aligned: the tick column's unit caption occupies the
	// top-right corner and the two overlapped.
	fmt.Fprintf(&b, "%s create text %d %d -text %s -anchor nw -fill $::tkfg -font TkSmallFont\n",
		tkTrendCanvas, lx+10, ly, ref(c.Span))

	// Hour average first, so the immediate rate curve lies on top of it
	tkTrendLine(&b, c.Hour, tkColorHour)
	tkTrendLine(&b, c.Rate, tkColorRate)

	// Hover readout on top: a guide line down the hovered bucket and a box with its
	// numbers — the desktop form of the web panel's <title> per column.
	if hov := tkTrendState.hover; hov >= 0 && hov < len(c.Cols) {
		col := c.Cols[hov]
		fmt.Fprintf(&b, "%s create line %d %d %d %d -fill %s -width 1\n",
			tkTrendCanvas, col.X, c.PlotTop, col.X, c.PlotBottom, tkColorGrid)

		// The box is created around the text rather than measured first: bbox asks
		// Tk for the real wrapped size, then the rectangle is lowered behind it.
		// Anchored at the plot top because the wrapped text is at most a few lines
		// and that is always inside the canvas.
		bx := int(col.X) + 12
		if bx+trendTipW > w-4 {
			bx = int(col.X) - 12 - trendTipW
		}
		if bx < 4 {
			bx = 4
		}
		fmt.Fprintf(&b, "set ::ttip [%s create text %d %d -text %s -anchor nw -width %d -justify left -fill $::tkfg -font TkSmallFont]\n",
			tkTrendCanvas, bx+7, c.PlotTop+5, ref(c.HoverTip(hov)), trendTipW-14)
		fmt.Fprintf(&b, "set ::tbb [%s bbox $::ttip]\n", tkTrendCanvas)
		fmt.Fprintf(&b, "set ::trid [%s create rectangle [expr {[lindex $::tbb 0]-7}] [expr {[lindex $::tbb 1]-5}] [expr {[lindex $::tbb 2]+7}] [expr {[lindex $::tbb 3]+5}] -fill %s -outline %s]\n",
			tkTrendCanvas, tkColorTipBg, tkColorGrid)
		fmt.Fprintf(&b, "%s lower $::trid $::ttip\n", tkTrendCanvas)
	}

	tkEval(b.String())
}

// tkTrendMotion tracks the pointer over the chart (bound to <Motion>). The event's
// X/Y are already relative to the canvas, which is what the layout expects.
func tkTrendMotion(e *Event) {
	w, h := tkWidgetSize(tkTrendCanvas)
	if w < 2 || h < 2 {
		return
	}
	st := snapshotStatus()
	c := buildTrendChart(st.KillTrend, st.TrendWindowText, int32(w), int32(h))
	if col := c.ColumnAt(int32(e.X), int32(e.Y)); col != tkTrendState.hover {
		tkTrendState.hover, tkTrendState.stale = col, true
		// Redraw now: leaving it to the 500ms tick would make the readout trail the
		// pointer, which reads as a broken tooltip.
		tkDrawTrend(st)
	}
}

// tkTrendLeave clears the readout when the pointer leaves the canvas, otherwise the
// last box stays on screen with nothing under the cursor.
func tkTrendLeave(e *Event) {
	if tkTrendState.hover >= 0 {
		tkTrendState.hover, tkTrendState.stale = -1, true
		tkDrawTrend(snapshotStatus())
	}
}

// Trend chart colours: the same two hues the Win32 build and the web panel use.
const (
	tkColorGrid = "#909090"
	tkColorRate = "#0E7A2A" // kill rate (10 min, extrapolated)
	tkColorHour = "#005AC0" // kills in the last hour

	// Hover readout box. The fill follows the theme so it does not glare under a
	// dark one; Tk has no system tooltip colour to borrow (Win32 does, and uses it).
	tkColorTipBg = "#ffffe1"
)

// tkTrendLine appends one create line command for a whole series. Passing every
// vertex in a single command matters: one item moves, scales and redraws as a unit.
func tkTrendLine(b *strings.Builder, pts []trendXY, color string) {
	if len(pts) < 2 {
		return
	}
	fmt.Fprintf(b, "%s create line", tkTrendCanvas)
	for _, p := range pts {
		fmt.Fprintf(b, " %d %d", p.X, p.Y)
	}
	fmt.Fprintf(b, " -fill %s -width 2 -smooth 0\n", color)
}

// tkWidgetSize reports a widget's current pixel size (0,0 when not mapped yet).
func tkWidgetSize(path string) (w, h int) {
	ws, err := Eval("winfo width " + path)
	if err != nil {
		return 0, 0
	}
	hs, err := Eval("winfo height " + path)
	if err != nil {
		return 0, 0
	}
	w, _ = strconv.Atoi(strings.TrimSpace(ws))
	h, _ = strconv.Atoi(strings.TrimSpace(hs))
	return w, h
}

// tkFontWidth measures a string already stored in a Tcl variable (varRef, e.g.
// "$::tv0"). One seek later a legend can be laid out without guessing.
func tkFontWidth(font, varRef string) int {
	s, err := Eval(fmt.Sprintf("font measure %s %s", font, varRef))
	if err != nil {
		return 0
	}
	n, _ := strconv.Atoi(strings.TrimSpace(s))
	return n
}

// tkOpen opens a file or URL with the system default handler (rundll32 on Windows,
// xdg-open on Linux).
func tkOpen(target string) {
	var cmd *exec.Cmd
	if runtime.GOOS == "windows" {
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", target)
	} else {
		cmd = exec.Command("xdg-open", target)
	}
	if err := cmd.Start(); err != nil {
		log.Println(T("log.tk_open_failed", target, err))
	}
}

// openPanel opens the web panel with the system browser. The "open web" button and a click on
// the status bar's HTTP cell (which shows the address) both land here, so the disabled case is
// explained in exactly one place — a dead click shouldn't read as a broken app.
func openPanel() {
	if !cfg.EnablePanel {
		tkEval(`tk_messageBox -title "` + T("gui.panel_disabled_title") + `" -icon info ` +
			`-message "` + T("gui.panel_disabled_msg") + `"`)
		return
	}
	tkOpen(panelURL())
}

// runTk initializes Tcl/Tk (tk9.0 unpacks the runtime into the user cache dir),
// builds the window and enters the event loop. Closing the window triggers the
// WmProtocol callback, which os.Exit()s directly.
func runTk() {
	runtime.LockOSThread()    // tk9.0 requires init and all Tk calls on one thread
	ErrorMode = CollectErrors // collect errors from individual Tcl calls instead of panicking

	// Enable the raw Tcl eval extension (must come before the first Eval).
	if err := InitializeExtension("eval"); err != nil {
		log.Println(T("log.tk_eval_init_failed", err))
		return
	}

	if err := tkEval(buildUIScript()); err != nil {
		log.Println(T("log.tk_build_failed", err))
		return
	}

	// Tab and status-line initial text depend on the language (the script fills one in first;
	// this overrides it with the current one).
	tkEval(`.nb tab 0 -text "` + T("tab.status") + `"`)
	tkEval(`.nb tab 1 -text "` + T("tab.data") + `"`)
	tkEval(`.nb tab 2 -text "` + T("panel.trend_title") + `"`)
	tkSetLabel(".nb.s.state", T("app.init"))

	// Bottom button row: native widgets + Command(func) callbacks, so no custom Tcl
	// command needs registering. The parent comes from the method receiver
	// (btns.TButton creates under btns); In() is a geometry-manager (grid/pack) option
	// and cannot be passed at widget creation (ttk::button rejects -in).
	btns := TFrame()
	Grid(btns, In(App), Row(2), Column(0), Sticky("ew"), Padx(8), Pady(6))
	btnCfg := btns.TButton(Txt(T("gui.open_config")), Command(func() { tkOpen(configPath()) }))
	btnWeb := btns.TButton(Txt(T("gui.open_web")), Command(func() { openPanel() }))
	btnExit := btns.TButton(Txt(T("gui.exit")), Command(func() { os.Exit(0) }))
	Grid(btnCfg, In(btns), Row(0), Column(0), Padx(6))
	Grid(btnWeb, In(btns), Row(0), Column(1), Padx(6))
	Grid(btnExit, In(btns), Row(0), Column(2), Padx(6))

	// Bottom status bar: same shared source as the Win32 build (statusBarParts). Filled here
	// for the first time so the bar isn't blank until the first refresh tick, then kept up to
	// date by tkStatusBar inside tkRefresh.
	tkStatusBar(snapshotStatus())

	// Chart hover: the canvas reports pointer movement, and the handler redraws with
	// the readout. Bind takes the canvas path as a tag and Command wraps a
	// func(*Event), the same pair the buttons use above — no custom Tcl command.
	Bind(tkTrendCanvas, "<Motion>", Command(tkTrendMotion))
	Bind(tkTrendCanvas, "<Leave>", Command(tkTrendLeave))

	// The status bar's address cell is a link (blue, underlined — see the Link.TLabel style and
	// SbLinkFont in the UI script): clicking it opens the panel, the same action as the button.
	Bind(".sb.p1", "<Button-1>", Command(func(*Event) { openPanel() }))

	// Window icon: largest first (the order Tk docs recommend).
	// Must happen before App.Wait() — if Wait finds no icon set, it installs a default
	// one, and setting it afterwards is overwritten (it only honors the first).
	App.IconPhoto(NewPhoto(Data(tkIcon256)), NewPhoto(Data(tkIcon48)), NewPhoto(Data(tkIcon16)))

	// Window close = exit the whole process (the monitoring backend goes with it).
	WmProtocol(App, "WM_DELETE_WINDOW", func() { os.Exit(0) })

	// Center the window.
	App.Center()

	// First refresh, which also starts the periodic refresh (self-rescheduled after).
	tkRefresh()

	// Enter the Tk event loop (normally never returns; close goes through the
	// WmProtocol callback → os.Exit).
	App.Wait()
}

// runUI is the tk entry point: start the HTTP panel server per config, then enter the
// Tk event loop.
func runUI() {
	if cfg.EnablePanel {
		log.Println(T("log.panel_addr", portOf(cfg.ListenAddr)))

		go func() {
			if err := http.ListenAndServe(cfg.ListenAddr, nil); err != nil {
				log.Println(T("log.panel_start_failed", err))
				setRuntimeError(T("log.panel_start_failed", err.Error()))
			}
		}()
	} else {
		// Panel disabled by config: don't even listen on the port; the UI's "open web"
		// button shows this message
		log.Println(T("log.panel_off_note"))
	}

	// toolbar_edge is implemented by the Win32 UI only: it needs the tray icon as a fallback
	// (otherwise a hidden main window would be unreachable) and window regions for the rounded
	// corners -- Tk has neither. Say so instead of silently ignoring the setting.
	if cfg.ToolbarEdge != "" {
		log.Println(T("log.toolbar_win32_only"))
	}

	runTk()
}

// ---- Tk logging sink: feeds only the shared ring buffer (shown on the status tab) ----

// runningTests reports whether the running binary is a go test build.
// On Windows the test binary is named xxx.test.exe, so checking ".test" alone misses it.
func runningTests() bool {
	base := strings.ToLower(filepath.Base(os.Args[0]))
	return strings.HasSuffix(base, ".test") || strings.HasSuffix(base, ".test.exe")
}

// startLogging redirects the log: in-memory ring buffer only, shown on the status tab.
// A GUI has no console, so the log is visible in the window; no log file next to the exe.
func startLogging() {
	if runningTests() {
		return
	}
	log.SetOutput(guiLogRing)
}
